version: '3.9'

services:
  api:
    build:
      dockerfile: PrhApi/Dockerfile
      context: ./src
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - AWS_REGION=eu-north-1
    volumes:
      - $HOME/.aws:/root/.aws:ro
    ports:
      - '6000:80'
      
