/*
 * PRH mock API
 *
 * API definition for PRH mock API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lassi.patanen@gofore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PrhApi.Models.CodeGen.Client.OpenAPIDateConverter;

namespace PrhApi.Models.CodeGen.Model
{
    /// <summary>
    /// BeneficialOwnersWriteRequest
    /// </summary>
    [DataContract(Name = "BeneficialOwnersWriteRequest")]
    public partial class BeneficialOwnersWriteRequest : IEquatable<BeneficialOwnersWriteRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BeneficialOwnersWriteRequest" /> class.
        /// </summary>
        /// <param name="businessId">businessId.</param>
        /// <param name="beneficialOwners">beneficialOwners.</param>
        public BeneficialOwnersWriteRequest(string businessId = default(string), BeneficialOwnersResponse beneficialOwners = default(BeneficialOwnersResponse))
        {
            this.BusinessId = businessId;
            this.BeneficialOwners = beneficialOwners;
        }

        /// <summary>
        /// Gets or Sets BusinessId
        /// </summary>
        [DataMember(Name = "businessId", EmitDefaultValue = false)]
        public string BusinessId { get; set; }

        /// <summary>
        /// Gets or Sets BeneficialOwners
        /// </summary>
        [DataMember(Name = "beneficialOwners", EmitDefaultValue = false)]
        public BeneficialOwnersResponse BeneficialOwners { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BeneficialOwnersWriteRequest {\n");
            sb.Append("  BusinessId: ").Append(BusinessId).Append("\n");
            sb.Append("  BeneficialOwners: ").Append(BeneficialOwners).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BeneficialOwnersWriteRequest);
        }

        /// <summary>
        /// Returns true if BeneficialOwnersWriteRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of BeneficialOwnersWriteRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BeneficialOwnersWriteRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.BusinessId == input.BusinessId ||
                    (this.BusinessId != null &&
                    this.BusinessId.Equals(input.BusinessId))
                ) && 
                (
                    this.BeneficialOwners == input.BeneficialOwners ||
                    (this.BeneficialOwners != null &&
                    this.BeneficialOwners.Equals(input.BeneficialOwners))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BusinessId != null)
                {
                    hashCode = (hashCode * 59) + this.BusinessId.GetHashCode();
                }
                if (this.BeneficialOwners != null)
                {
                    hashCode = (hashCode * 59) + this.BeneficialOwners.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
