/*
 * PRH mock API
 *
 * API definition for PRH mock API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lassi.patanen@gofore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PrhApi.Models.CodeGen.Client.OpenAPIDateConverter;

namespace PrhApi.Models.CodeGen.Model
{
    /// <summary>
    /// BeneficialOwnerShareSeries
    /// </summary>
    [DataContract(Name = "BeneficialOwnerShareSeries")]
    public partial class BeneficialOwnerShareSeries : IEquatable<BeneficialOwnerShareSeries>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BeneficialOwnerShareSeries" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BeneficialOwnerShareSeries() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BeneficialOwnerShareSeries" /> class.
        /// </summary>
        /// <param name="shareSeriesClass">shareSeriesClass (required).</param>
        /// <param name="numberOfShares">numberOfShares (required).</param>
        /// <param name="votesPerShare">votesPerShare (required).</param>
        public BeneficialOwnerShareSeries(string shareSeriesClass = default(string), int numberOfShares = default(int), int votesPerShare = default(int))
        {
            // to ensure "shareSeriesClass" is required (not null)
            if (shareSeriesClass == null)
            {
                throw new ArgumentNullException("shareSeriesClass is a required property for BeneficialOwnerShareSeries and cannot be null");
            }
            this.ShareSeriesClass = shareSeriesClass;
            this.NumberOfShares = numberOfShares;
            this.VotesPerShare = votesPerShare;
        }

        /// <summary>
        /// Gets or Sets ShareSeriesClass
        /// </summary>
        [DataMember(Name = "shareSeriesClass", IsRequired = true, EmitDefaultValue = true)]
        public string ShareSeriesClass { get; set; }

        /// <summary>
        /// Gets or Sets NumberOfShares
        /// </summary>
        [DataMember(Name = "numberOfShares", IsRequired = true, EmitDefaultValue = true)]
        public int NumberOfShares { get; set; }

        /// <summary>
        /// Gets or Sets VotesPerShare
        /// </summary>
        [DataMember(Name = "votesPerShare", IsRequired = true, EmitDefaultValue = true)]
        public int VotesPerShare { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BeneficialOwnerShareSeries {\n");
            sb.Append("  ShareSeriesClass: ").Append(ShareSeriesClass).Append("\n");
            sb.Append("  NumberOfShares: ").Append(NumberOfShares).Append("\n");
            sb.Append("  VotesPerShare: ").Append(VotesPerShare).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BeneficialOwnerShareSeries);
        }

        /// <summary>
        /// Returns true if BeneficialOwnerShareSeries instances are equal
        /// </summary>
        /// <param name="input">Instance of BeneficialOwnerShareSeries to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BeneficialOwnerShareSeries input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ShareSeriesClass == input.ShareSeriesClass ||
                    (this.ShareSeriesClass != null &&
                    this.ShareSeriesClass.Equals(input.ShareSeriesClass))
                ) && 
                (
                    this.NumberOfShares == input.NumberOfShares ||
                    this.NumberOfShares.Equals(input.NumberOfShares)
                ) && 
                (
                    this.VotesPerShare == input.VotesPerShare ||
                    this.VotesPerShare.Equals(input.VotesPerShare)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShareSeriesClass != null)
                {
                    hashCode = (hashCode * 59) + this.ShareSeriesClass.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.NumberOfShares.GetHashCode();
                hashCode = (hashCode * 59) + this.VotesPerShare.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
