/*
 * PRH mock API
 *
 * API definition for PRH mock API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lassi.patanen@gofore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PrhApi.Models.CodeGen.Client.OpenAPIDateConverter;

namespace PrhApi.Models.CodeGen.Model
{
    /// <summary>
    /// Beneficial Owners response model
    /// </summary>
    [DataContract(Name = "BeneficialOwnersResponse")]
    public partial class BeneficialOwnersResponse : IEquatable<BeneficialOwnersResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BeneficialOwnersResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BeneficialOwnersResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BeneficialOwnersResponse" /> class.
        /// </summary>
        /// <param name="shareSeries">shareSeries (required).</param>
        /// <param name="shareholder">shareholder (required).</param>
        public BeneficialOwnersResponse(List<BeneficialOwnerShareSeries> shareSeries = default(List<BeneficialOwnerShareSeries>), List<Shareholder> shareholder = default(List<Shareholder>))
        {
            // to ensure "shareSeries" is required (not null)
            if (shareSeries == null)
            {
                throw new ArgumentNullException("shareSeries is a required property for BeneficialOwnersResponse and cannot be null");
            }
            this.ShareSeries = shareSeries;
            // to ensure "shareholder" is required (not null)
            if (shareholder == null)
            {
                throw new ArgumentNullException("shareholder is a required property for BeneficialOwnersResponse and cannot be null");
            }
            this.Shareholder = shareholder;
        }

        /// <summary>
        /// Gets or Sets ShareSeries
        /// </summary>
        [DataMember(Name = "shareSeries", IsRequired = true, EmitDefaultValue = true)]
        public List<BeneficialOwnerShareSeries> ShareSeries { get; set; }

        /// <summary>
        /// Gets or Sets Shareholder
        /// </summary>
        [DataMember(Name = "shareholder", IsRequired = true, EmitDefaultValue = true)]
        public List<Shareholder> Shareholder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BeneficialOwnersResponse {\n");
            sb.Append("  ShareSeries: ").Append(ShareSeries).Append("\n");
            sb.Append("  Shareholder: ").Append(Shareholder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BeneficialOwnersResponse);
        }

        /// <summary>
        /// Returns true if BeneficialOwnersResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of BeneficialOwnersResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BeneficialOwnersResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ShareSeries == input.ShareSeries ||
                    this.ShareSeries != null &&
                    input.ShareSeries != null &&
                    this.ShareSeries.SequenceEqual(input.ShareSeries)
                ) && 
                (
                    this.Shareholder == input.Shareholder ||
                    this.Shareholder != null &&
                    input.Shareholder != null &&
                    this.Shareholder.SequenceEqual(input.Shareholder)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShareSeries != null)
                {
                    hashCode = (hashCode * 59) + this.ShareSeries.GetHashCode();
                }
                if (this.Shareholder != null)
                {
                    hashCode = (hashCode * 59) + this.Shareholder.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
