/*
 * PRH mock API
 *
 * API definition for PRH mock API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lassi.patanen@gofore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PrhApi.Models.CodeGen.Client.OpenAPIDateConverter;

namespace PrhApi.Models.CodeGen.Model
{
    /// <summary>
    /// BoardMember
    /// </summary>
    [DataContract(Name = "BoardMember")]
    public partial class BoardMember : IEquatable<BoardMember>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BoardMember" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BoardMember() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BoardMember" /> class.
        /// </summary>
        /// <param name="role">role (required).</param>
        /// <param name="givenName">givenName (required).</param>
        /// <param name="middleNames">middleNames (required).</param>
        /// <param name="lastName">lastName (required).</param>
        /// <param name="dateOfBirth">dateOfBirth (required).</param>
        /// <param name="nationality">nationality (required).</param>
        public BoardMember(string role = default(string), string givenName = default(string), string middleNames = default(string), string lastName = default(string), string dateOfBirth = default(string), string nationality = default(string))
        {
            // to ensure "role" is required (not null)
            if (role == null)
            {
                throw new ArgumentNullException("role is a required property for BoardMember and cannot be null");
            }
            this.Role = role;
            // to ensure "givenName" is required (not null)
            if (givenName == null)
            {
                throw new ArgumentNullException("givenName is a required property for BoardMember and cannot be null");
            }
            this.GivenName = givenName;
            // to ensure "middleNames" is required (not null)
            if (middleNames == null)
            {
                throw new ArgumentNullException("middleNames is a required property for BoardMember and cannot be null");
            }
            this.MiddleNames = middleNames;
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new ArgumentNullException("lastName is a required property for BoardMember and cannot be null");
            }
            this.LastName = lastName;
            // to ensure "dateOfBirth" is required (not null)
            if (dateOfBirth == null)
            {
                throw new ArgumentNullException("dateOfBirth is a required property for BoardMember and cannot be null");
            }
            this.DateOfBirth = dateOfBirth;
            // to ensure "nationality" is required (not null)
            if (nationality == null)
            {
                throw new ArgumentNullException("nationality is a required property for BoardMember and cannot be null");
            }
            this.Nationality = nationality;
        }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", IsRequired = true, EmitDefaultValue = true)]
        public string Role { get; set; }

        /// <summary>
        /// Gets or Sets GivenName
        /// </summary>
        [DataMember(Name = "givenName", IsRequired = true, EmitDefaultValue = true)]
        public string GivenName { get; set; }

        /// <summary>
        /// Gets or Sets MiddleNames
        /// </summary>
        [DataMember(Name = "middleNames", IsRequired = true, EmitDefaultValue = true)]
        public string MiddleNames { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [DataMember(Name = "lastName", IsRequired = true, EmitDefaultValue = true)]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets DateOfBirth
        /// </summary>
        [DataMember(Name = "dateOfBirth", IsRequired = true, EmitDefaultValue = true)]
        public string DateOfBirth { get; set; }

        /// <summary>
        /// Gets or Sets Nationality
        /// </summary>
        [DataMember(Name = "nationality", IsRequired = true, EmitDefaultValue = true)]
        public string Nationality { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BoardMember {\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  GivenName: ").Append(GivenName).Append("\n");
            sb.Append("  MiddleNames: ").Append(MiddleNames).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  DateOfBirth: ").Append(DateOfBirth).Append("\n");
            sb.Append("  Nationality: ").Append(Nationality).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BoardMember);
        }

        /// <summary>
        /// Returns true if BoardMember instances are equal
        /// </summary>
        /// <param name="input">Instance of BoardMember to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BoardMember input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Role == input.Role ||
                    (this.Role != null &&
                    this.Role.Equals(input.Role))
                ) && 
                (
                    this.GivenName == input.GivenName ||
                    (this.GivenName != null &&
                    this.GivenName.Equals(input.GivenName))
                ) && 
                (
                    this.MiddleNames == input.MiddleNames ||
                    (this.MiddleNames != null &&
                    this.MiddleNames.Equals(input.MiddleNames))
                ) && 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.DateOfBirth == input.DateOfBirth ||
                    (this.DateOfBirth != null &&
                    this.DateOfBirth.Equals(input.DateOfBirth))
                ) && 
                (
                    this.Nationality == input.Nationality ||
                    (this.Nationality != null &&
                    this.Nationality.Equals(input.Nationality))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Role != null)
                {
                    hashCode = (hashCode * 59) + this.Role.GetHashCode();
                }
                if (this.GivenName != null)
                {
                    hashCode = (hashCode * 59) + this.GivenName.GetHashCode();
                }
                if (this.MiddleNames != null)
                {
                    hashCode = (hashCode * 59) + this.MiddleNames.GetHashCode();
                }
                if (this.LastName != null)
                {
                    hashCode = (hashCode * 59) + this.LastName.GetHashCode();
                }
                if (this.DateOfBirth != null)
                {
                    hashCode = (hashCode * 59) + this.DateOfBirth.GetHashCode();
                }
                if (this.Nationality != null)
                {
                    hashCode = (hashCode * 59) + this.Nationality.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // GivenName (string) maxLength
            if (this.GivenName != null && this.GivenName.Length > 250)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for GivenName, length must be less than 250.", new [] { "GivenName" });
            }

            // MiddleNames (string) maxLength
            if (this.MiddleNames != null && this.MiddleNames.Length > 250)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MiddleNames, length must be less than 250.", new [] { "MiddleNames" });
            }

            // LastName (string) maxLength
            if (this.LastName != null && this.LastName.Length > 250)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LastName, length must be less than 250.", new [] { "LastName" });
            }

            // Nationality (string) maxLength
            if (this.Nationality != null && this.Nationality.Length > 3)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Nationality, length must be less than 3.", new [] { "Nationality" });
            }

            // Nationality (string) minLength
            if (this.Nationality != null && this.Nationality.Length < 3)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Nationality, length must be greater than 3.", new [] { "Nationality" });
            }

            yield break;
        }
    }

}
