/*
 * PRH mock API
 *
 * API definition for PRH mock API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lassi.patanen@gofore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PrhApi.Models.CodeGen.Client.OpenAPIDateConverter;

namespace PrhApi.Models.CodeGen.Model
{
    /// <summary>
    /// An enumeration.
    /// </summary>
    /// <value>An enumeration.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LegalStatus
    {
        /// <summary>
        /// Enum NORMAL for value: NORMAL
        /// </summary>
        [EnumMember(Value = "NORMAL")]
        NORMAL = 1,

        /// <summary>
        /// Enum LIQUIDATION for value: LIQUIDATION
        /// </summary>
        [EnumMember(Value = "LIQUIDATION")]
        LIQUIDATION = 2,

        /// <summary>
        /// Enum RESTRUCTURING for value: RESTRUCTURING
        /// </summary>
        [EnumMember(Value = "RESTRUCTURING")]
        RESTRUCTURING = 3,

        /// <summary>
        /// Enum BANKRUPTCY for value: BANKRUPTCY
        /// </summary>
        [EnumMember(Value = "BANKRUPTCY")]
        BANKRUPTCY = 4

    }

}
