/*
 * PRH mock API
 *
 * API definition for PRH mock API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lassi.patanen@gofore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PrhApi.Models.CodeGen.Client.OpenAPIDateConverter;

namespace PrhApi.Models.CodeGen.Model
{
    /// <summary>
    /// ShareSeries
    /// </summary>
    [DataContract(Name = "ShareSeries")]
    public partial class ShareSeries : IEquatable<ShareSeries>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShareSeries" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShareSeries() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShareSeries" /> class.
        /// </summary>
        /// <param name="shareSeriesClass">shareSeriesClass (required).</param>
        /// <param name="numberOfShares">numberOfShares (required).</param>
        /// <param name="shareValues">shareValues (required).</param>
        /// <param name="shareValueCurrency">shareValueCurrency.</param>
        public ShareSeries(string shareSeriesClass = default(string), int numberOfShares = default(int), decimal shareValues = default(decimal), string shareValueCurrency = default(string))
        {
            // to ensure "shareSeriesClass" is required (not null)
            if (shareSeriesClass == null)
            {
                throw new ArgumentNullException("shareSeriesClass is a required property for ShareSeries and cannot be null");
            }
            this.ShareSeriesClass = shareSeriesClass;
            this.NumberOfShares = numberOfShares;
            this.ShareValues = shareValues;
            this.ShareValueCurrency = shareValueCurrency;
        }

        /// <summary>
        /// Gets or Sets ShareSeriesClass
        /// </summary>
        [DataMember(Name = "shareSeriesClass", IsRequired = true, EmitDefaultValue = true)]
        public string ShareSeriesClass { get; set; }

        /// <summary>
        /// Gets or Sets NumberOfShares
        /// </summary>
        [DataMember(Name = "numberOfShares", IsRequired = true, EmitDefaultValue = true)]
        public int NumberOfShares { get; set; }

        /// <summary>
        /// Gets or Sets ShareValues
        /// </summary>
        [DataMember(Name = "shareValues", IsRequired = true, EmitDefaultValue = true)]
        public decimal ShareValues { get; set; }

        /// <summary>
        /// Gets or Sets ShareValueCurrency
        /// </summary>
        [DataMember(Name = "shareValueCurrency", EmitDefaultValue = false)]
        public string ShareValueCurrency { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShareSeries {\n");
            sb.Append("  ShareSeriesClass: ").Append(ShareSeriesClass).Append("\n");
            sb.Append("  NumberOfShares: ").Append(NumberOfShares).Append("\n");
            sb.Append("  ShareValues: ").Append(ShareValues).Append("\n");
            sb.Append("  ShareValueCurrency: ").Append(ShareValueCurrency).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ShareSeries);
        }

        /// <summary>
        /// Returns true if ShareSeries instances are equal
        /// </summary>
        /// <param name="input">Instance of ShareSeries to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ShareSeries input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ShareSeriesClass == input.ShareSeriesClass ||
                    (this.ShareSeriesClass != null &&
                    this.ShareSeriesClass.Equals(input.ShareSeriesClass))
                ) && 
                (
                    this.NumberOfShares == input.NumberOfShares ||
                    this.NumberOfShares.Equals(input.NumberOfShares)
                ) && 
                (
                    this.ShareValues == input.ShareValues ||
                    this.ShareValues.Equals(input.ShareValues)
                ) && 
                (
                    this.ShareValueCurrency == input.ShareValueCurrency ||
                    (this.ShareValueCurrency != null &&
                    this.ShareValueCurrency.Equals(input.ShareValueCurrency))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShareSeriesClass != null)
                {
                    hashCode = (hashCode * 59) + this.ShareSeriesClass.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.NumberOfShares.GetHashCode();
                hashCode = (hashCode * 59) + this.ShareValues.GetHashCode();
                if (this.ShareValueCurrency != null)
                {
                    hashCode = (hashCode * 59) + this.ShareValueCurrency.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
