/*
 * PRH mock API
 *
 * API definition for PRH mock API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lassi.patanen@gofore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PrhApi.Models.CodeGen.Client.OpenAPIDateConverter;

namespace PrhApi.Models.CodeGen.Model
{
    /// <summary>
    /// SignatoryRightsResponse
    /// </summary>
    [DataContract(Name = "SignatoryRightsResponse")]
    public partial class SignatoryRightsResponse : IEquatable<SignatoryRightsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignatoryRightsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignatoryRightsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignatoryRightsResponse" /> class.
        /// </summary>
        /// <param name="signatoryRights">signatoryRights (required).</param>
        public SignatoryRightsResponse(List<SigningRights> signatoryRights = default(List<SigningRights>))
        {
            // to ensure "signatoryRights" is required (not null)
            if (signatoryRights == null)
            {
                throw new ArgumentNullException("signatoryRights is a required property for SignatoryRightsResponse and cannot be null");
            }
            this.SignatoryRights = signatoryRights;
        }

        /// <summary>
        /// Gets or Sets SignatoryRights
        /// </summary>
        [DataMember(Name = "signatoryRights", IsRequired = true, EmitDefaultValue = true)]
        public List<SigningRights> SignatoryRights { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignatoryRightsResponse {\n");
            sb.Append("  SignatoryRights: ").Append(SignatoryRights).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SignatoryRightsResponse);
        }

        /// <summary>
        /// Returns true if SignatoryRightsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SignatoryRightsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SignatoryRightsResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SignatoryRights == input.SignatoryRights ||
                    this.SignatoryRights != null &&
                    input.SignatoryRights != null &&
                    this.SignatoryRights.SequenceEqual(input.SignatoryRights)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SignatoryRights != null)
                {
                    hashCode = (hashCode * 59) + this.SignatoryRights.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
