/*
 * PRH mock API
 *
 * API definition for PRH mock API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lassi.patanen@gofore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PrhApi.Models.CodeGen.Client.OpenAPIDateConverter;

namespace PrhApi.Models.CodeGen.Model
{
    /// <summary>
    /// SignatoryRightsResponse
    /// </summary>
    [DataContract(Name = "SignatoryRightsResponse")]
    public partial class SignatoryRightsResponse : IEquatable<SignatoryRightsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignatoryRightsResponse" /> class.
        /// </summary>
        /// <param name="signingRights">signingRights.</param>
        public SignatoryRightsResponse(List<SigningRights> signingRights = default(List<SigningRights>))
        {
            this.SigningRights = signingRights;
        }

        /// <summary>
        /// Gets or Sets SigningRights
        /// </summary>
        [DataMember(Name = "signingRights", EmitDefaultValue = false)]
        public List<SigningRights> SigningRights { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignatoryRightsResponse {\n");
            sb.Append("  SigningRights: ").Append(SigningRights).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SignatoryRightsResponse);
        }

        /// <summary>
        /// Returns true if SignatoryRightsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SignatoryRightsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SignatoryRightsResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SigningRights == input.SigningRights ||
                    this.SigningRights != null &&
                    input.SigningRights != null &&
                    this.SigningRights.SequenceEqual(input.SigningRights)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SigningRights != null)
                {
                    hashCode = (hashCode * 59) + this.SigningRights.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
